language: python
# cache package wheels (1 cache per python version)
cache: pip
# newer python versions are available only on xenial (while some older only on trusty) Ubuntu distribution
dist: xenial
sudo: required

jobs:
  include:
  - name: "run test suite with python 3.6"
    python: 3.6
    script: |
      set -e
      pytest
  - name: "run test suite with python 3.7"
    python: 3.7
    script: |
      set -e
      pytest
  - name: "run test suite with python 3.8"
    python: 3.8
    script: |
      set -e
      pytest

  - name: "typecheck with mypy"
    python: 3.7
    script: |
      set -e
      mypy .

  - name: Lint with black
    python: 3.7
    script: 'black --check pytest_mypy_plugins setup.py'
  - name: Lint with isort
    python: 3.7
    script: 'isort --check --diff'

before_install: |
  # Upgrade pip, setuptools, and wheel
  pip install -U pip setuptools wheel

install: |
  pip install -r dev-requirements.txt
